name: PR_unit_tests

on:
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'dev_danil'

jobs:
  Unit-test:
    name: Run unit tests on PR in main
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # Установка Java и Gradle
      - name: Setup Java and Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          gradle-version: 8.2.2

      # Предоставление разрешения на выполнение файла gradlew
      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/tests/testDebugUnitTest/index.html

      - name: Upload test report directory
        uses: actions/upload-artifact@v2
        with:
          name: testDebugStuff
          path: app/build/reports/tests/testDebugUnitTest/
          if-no-files-found: warn
