name: Unit Tests

on:
  push:
    branches:
      - main
      - dev
      - dev_danil
  pull_request:
    branches:
      - main     
      - dev
      - dev_danil

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with: {java-version: 1.8}

    - name: Run unit tests
      run: ./gradlew test
